### ISSUE TITLE
Замінити API лінк на сервіс тривог

### ISSUE THREAD

**Issue by Vadimkin** [sweetpalma/petlyuryk#14]
Привіт!

Якщо все ще використовуєте API повітряних тривог, то замініть, будь ласка, `https://emapa.fra1.cdn.digitaloceanspaces.com/statuses.json` → `https://vadimklimenko.com/map/statuses.json`, там повністю відповідь 1-в-1. Приблизно через тиждень я перестану оновлювати файл на DO Spaces (перший лінк).

Дякую!

https://github.com/sweetpalma/petlyuryk/blob/51b5082fe139aa0baf8fbec119ddbf9d4c56da63/src/neural/modules/module-ua-alert.ts#L9-L13

**Comment by sweetpalma** [comment]
Вітаю! Велике дякую вам за прекрасний АРІ і за дане завчасне повідомлення. На жаль, я лінива дупа і виправив це лише зараз - але тим не менш, краще пізно ніж ніколи.
Дякую!
